FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

COPY /platon/server/nginx.dev.conf /etc/nginx/nginx.conf

RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log
